export const historyData = [
  {
    id: 1,
    title: "Two Sum",
    language: "Java",
    difficulty: "Easy",
    time: "Today, 10:42 AM",
    createdAt: "2026-08-07T10:42:00",
  },
  {
    id: 2,
    title: "Binary Tree Level Order Traversal",
    language: "Java",
    difficulty: "Medium",
    time: "Yesterday, 8:40 PM",
    createdAt: "2026-08-06T20:40:00",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    language: "C++",
    difficulty: "Medium",
    time: "1 week ago",
    createdAt: "2026-07-31T14:20:00",
  },
  {
    id: 4,
    title: "Valid Parentheses",
    language: "Java",
    difficulty: "Easy",
    time: "3 days ago",
    createdAt: "2026-08-04T11:15:00",
  },
  {
    id: 5,
    title: "Merge Two Sorted Lists",
    language: "Python",
    difficulty: "Easy",
    time: "5 days ago",
    createdAt: "2026-08-02T16:30:00",
  },
  {
    id: 6,
    title: "Product of Array Except Self",
    language: "C++",
    difficulty: "Hard",
    time: "1 week ago",
    createdAt: "2026-07-30T09:50:00",
  },
];